export type Database = {
  public: {
    Tables: {
      pricing_config: {
        Row: {
          plan_slug: string;
          display_name: string;
          monthly_price_cents: number;
          max_active_recipes: number;
          webhooks_enabled: boolean;
          ghl_cache_ttl_seconds: number;
          rate_limit_priority: "low" | "standard" | "high";
          stripe_price_id: string | null;
          features: Record<string, unknown>;
          is_active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          plan_slug: string;
          display_name: string;
          monthly_price_cents: number;
          max_active_recipes?: number;
          webhooks_enabled?: boolean;
          ghl_cache_ttl_seconds?: number;
          rate_limit_priority?: "low" | "standard" | "high";
          stripe_price_id?: string | null;
          features?: Record<string, unknown>;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["pricing_config"]["Insert"]>;
      };
      accounts: {
        Row: {
          id: string;
          owner_user_id: string;
          business_name: string;
          phone: string | null;
          email: string | null;
          address_city: string | null;
          address_state: string | null;
          address_zip: string | null;
          vertical: "hvac" | "plumbing" | "electrical" | "roofing" | "landscaping" | null;
          business_hours: Record<string, unknown>;
          ghl_location_id: string | null;
          ghl_webhook_secret: string | null;
          ghl_token_encrypted: string | null;
          ghl_pit_encrypted: string | null;
          ghl_pit_scopes: string | null;
          ghl_pit_updated_at: string | null;
          ghl_voice_agent_id: string | null;
          onboarding_done_at: string | null;
          trial_ends_at: string | null;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          plan_slug: string;
          provisioning_status: "pending" | "in_progress" | "complete" | "error";
          provisioning_error: string | null;
          provisioning_completed_at: string | null;
          ghl_provisioning_status: "pending" | "in_progress" | "complete" | "failed";
          ghl_provisioning_error: string | null;
          ghl_health_status: string;
          ghl_last_health_check: string | null;
          elevenlabs_voice_id: string | null;
          voice_gender: "male" | "female" | null;
          greeting_text: string | null;
          greeting_name: string | null;
          greeting_audio_url: string | null;
          notification_contact_name: string | null;
          notification_contact_phone: string | null;
          notification_preferences: Record<string, unknown>;
          onboarding_step: number;
          onboarding_completed_at: string | null;
          activate_recipe_1: boolean;
          subscription_status: "trialing" | "active" | "past_due" | "canceled" | "paused";
          created_at: string;
          service_area: string | null;
          voice_greeting: string | null;
          notification_sms: boolean;
          notification_email: boolean;
          notification_contact: string | null;
          provisioning_step: number;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_user_id: string;
          business_name?: string;
          phone?: string | null;
          email?: string | null;
          address_city?: string | null;
          address_state?: string | null;
          address_zip?: string | null;
          vertical?: "hvac" | "plumbing" | "electrical" | "roofing" | "landscaping" | null;
          business_hours?: Record<string, unknown>;
          ghl_location_id?: string | null;
          ghl_webhook_secret?: string | null;
          ghl_token_encrypted?: string | null;
          ghl_pit_encrypted?: string | null;
          ghl_pit_scopes?: string | null;
          ghl_pit_updated_at?: string | null;
          ghl_voice_agent_id?: string | null;
          onboarding_done_at?: string | null;
          trial_ends_at?: string | null;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          plan_slug?: string;
          provisioning_status?: "pending" | "in_progress" | "complete" | "error";
          provisioning_error?: string | null;
          provisioning_completed_at?: string | null;
          ghl_provisioning_status?: "pending" | "in_progress" | "complete" | "failed";
          ghl_provisioning_error?: string | null;
          ghl_health_status?: string;
          ghl_last_health_check?: string | null;
          elevenlabs_voice_id?: string | null;
          voice_gender?: "male" | "female" | null;
          greeting_text?: string | null;
          greeting_name?: string | null;
          greeting_audio_url?: string | null;
          notification_contact_name?: string | null;
          notification_contact_phone?: string | null;
          notification_preferences?: Record<string, unknown>;
          onboarding_step?: number;
          onboarding_completed_at?: string | null;
          activate_recipe_1?: boolean;
          subscription_status?: "trialing" | "active" | "past_due" | "canceled" | "paused";
          created_at?: string;
          service_area?: string | null;
          voice_greeting?: string | null;
          notification_sms?: boolean;
          notification_email?: boolean;
          notification_contact?: string | null;
          provisioning_step?: number;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["accounts"]["Insert"]>;
      };
      account_users: {
        Row: {
          id: string;
          account_id: string;
          user_id: string;
          role: "admin" | "viewer";
          created_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          user_id: string;
          role?: "admin" | "viewer";
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["account_users"]["Insert"]>;
      };
      recipe_activations: {
        Row: {
          id: string;
          account_id: string;
          recipe_slug: string;
          status: "active" | "paused" | "error" | "deactivated";
          config: Record<string, unknown>;
          n8n_workflow_id: string | null;
          activated_at: string;
          last_triggered_at: string | null;
          deactivated_at: string | null;
          error_message: string | null;
        };
        Insert: {
          id?: string;
          account_id: string;
          recipe_slug: string;
          status?: "active" | "paused" | "error" | "deactivated";
          config?: Record<string, unknown>;
          n8n_workflow_id?: string | null;
          activated_at?: string;
          last_triggered_at?: string | null;
          deactivated_at?: string | null;
          error_message?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["recipe_activations"]["Insert"]>;
      };
      automation_events: {
        Row: {
          id: string;
          account_id: string;
          recipe_slug: string | null;
          event_type: string;
          ghl_event_type: string | null;
          ghl_event_id: string | null;
          contact_id: string | null;
          contact_phone: string | null;
          contact_name: string | null;
          summary: string;
          detail: Record<string, unknown>;
          created_at: string;
        };
        Insert: {
          id?: string;
          account_id: string;
          recipe_slug?: string | null;
          event_type: string;
          ghl_event_type?: string | null;
          ghl_event_id?: string | null;
          contact_id?: string | null;
          contact_phone?: string | null;
          contact_name?: string | null;
          summary: string;
          detail?: Record<string, unknown>;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["automation_events"]["Insert"]>;
      };
      integrations: {
        Row: {
          id: string;
          account_id: string;
          provider: "jobber" | "servicetitan" | "google_business" | "ghl" | "twilio" | "elevenlabs";
          status: "connected" | "disconnected" | "error";
          credentials_encrypted: Record<string, unknown> | null;
          metadata: Record<string, unknown>;
          connected_at: string | null;
          disconnected_at: string | null;
          error_message: string | null;
        };
        Insert: {
          id?: string;
          account_id: string;
          provider: "jobber" | "servicetitan" | "google_business" | "ghl" | "twilio" | "elevenlabs";
          status?: "connected" | "disconnected" | "error";
          credentials_encrypted?: Record<string, unknown> | null;
          metadata?: Record<string, unknown>;
          connected_at?: string | null;
          disconnected_at?: string | null;
          error_message?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["integrations"]["Insert"]>;
      };
      recipe_triggers: {
        Row: {
          id: string;
          account_id: string;
          recipe_slug: string;
          ghl_event_type: string;
          contact_id: string | null;
          fire_at: string;
          status: "queued" | "processing" | "completed" | "failed" | "cancelled";
          payload: Record<string, unknown> | null;
          attempt_count: number;
          max_attempts: number;
          last_error: string | null;
          processed_at: string | null;
          created_at: string;
          recipe_id: string | null;
          fired: boolean | null;
          trigger_data: Record<string, unknown> | null;
          retry_count: number | null;
        };
        Insert: {
          id?: string;
          account_id: string;
          recipe_slug: string;
          ghl_event_type: string;
          contact_id?: string | null;
          fire_at: string;
          status?: "queued" | "processing" | "completed" | "failed" | "cancelled";
          payload?: Record<string, unknown> | null;
          attempt_count?: number;
          max_attempts?: number;
          last_error?: string | null;
          processed_at?: string | null;
          created_at?: string;
          recipe_id?: string | null;
          fired?: boolean | null;
          trigger_data?: Record<string, unknown> | null;
          retry_count?: number | null;
        };
        Update: Partial<Database["public"]["Tables"]["recipe_triggers"]["Insert"]>;
      };
      stripe_processed_events: {
        Row: {
          event_id: string;
          event_type: string;
          processed_at: string;
        };
        Insert: {
          event_id: string;
          event_type: string;
          processed_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["stripe_processed_events"]["Insert"]>;
      };
    };
    Enums: {
      vertical: "hvac" | "plumbing" | "electrical" | "roofing" | "landscaping";
      provisioning_status: "pending" | "in_progress" | "complete" | "error";
      account_role: "admin" | "viewer";
      recipe_status: "active" | "paused" | "error" | "deactivated";
      integration_provider: "jobber" | "servicetitan" | "google_business" | "ghl" | "twilio" | "elevenlabs";
      integration_status: "connected" | "disconnected" | "error";
      rate_limit_priority: "low" | "standard" | "high";
      recipe_trigger_status: "queued" | "processing" | "completed" | "failed" | "cancelled";
    };
  };
};
